version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: olake_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    container_name: olake_kafka
    ports:
      - "9094:9092"
      - "9095:9093"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://host.docker.internal:9094,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: olake_zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
