services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: olake-mssql
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!123
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mssql-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password!123 -Q "SELECT 1" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

volumes:
  mssql-data:
