version: "3.8"

services:
  mysql-ssl:
    image: mysql:8.0
    container_name: olake_mysql-ssl-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: olake_mysql_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret1234
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3307:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./ssl-certs:/etc/mysql/ssl
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
      --binlog_row_metadata=FULL
      --max_allowed_packet=256M
      --innodb_buffer_pool_size=512M
      --default-authentication-plugin=mysql_native_password
      --require_secure_transport=ON
      --ssl-ca=/etc/mysql/ssl/ca-cert.pem
      --ssl-cert=/etc/mysql/ssl/server-cert.pem
      --ssl-key=/etc/mysql/ssl/server-key.pem
